-- 01_schema_oracle.sql
-- DDL compatível com Oracle: criação de esquema para planta, linhas, máquinas, tipos/unidades de sensor, sensores, leituras e rótulos.
-- Observação: ajuste o usuário/esquema conforme necessário no seu ambiente Oracle.

CREATE TABLE unit (
  unit_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR2(50)   NOT NULL,
  symbol        VARCHAR2(10)   NOT NULL
);

CREATE TABLE plant (
  plant_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR2(100)  NOT NULL
);

CREATE TABLE line (
  line_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plant_id      NUMBER          NOT NULL,
  name          VARCHAR2(100)   NOT NULL,
  CONSTRAINT fk_line_plant FOREIGN KEY (plant_id) REFERENCES plant(plant_id)
);

CREATE INDEX idx_line_plant ON line(plant_id);

CREATE TABLE machine (
  machine_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  line_id       NUMBER          NOT NULL,
  name          VARCHAR2(100)   NOT NULL,
  CONSTRAINT fk_machine_line FOREIGN KEY (line_id) REFERENCES line(line_id)
);

CREATE INDEX idx_machine_line ON machine(line_id);

CREATE TABLE sensor_type (
  sensor_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR2(50)   NOT NULL,
  expected_min   NUMBER,
  expected_max   NUMBER,
  unit_id        NUMBER,
  CONSTRAINT fk_sensor_type_unit FOREIGN KEY (unit_id) REFERENCES unit(unit_id)
);

CREATE INDEX idx_sensor_type_unit ON sensor_type(unit_id);

CREATE TABLE sensor (
  sensor_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  machine_id      NUMBER         NOT NULL,
  sensor_type_id  NUMBER         NOT NULL,
  serial          VARCHAR2(60)   UNIQUE NOT NULL,
  installed_at    TIMESTAMP(6)   NOT NULL,
  CONSTRAINT fk_sensor_machine FOREIGN KEY (machine_id) REFERENCES machine(machine_id),
  CONSTRAINT fk_sensor_type    FOREIGN KEY (sensor_type_id) REFERENCES sensor_type(sensor_type_id)
);

CREATE INDEX idx_sensor_machine ON sensor(machine_id);
CREATE INDEX idx_sensor_type ON sensor(sensor_type_id);

CREATE TABLE reading (
  reading_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sensor_id      NUMBER        NOT NULL,
  reading_time   TIMESTAMP(6)  NOT NULL,
  value          NUMBER        NOT NULL,
  CONSTRAINT fk_reading_sensor FOREIGN KEY (sensor_id) REFERENCES sensor(sensor_id)
);

CREATE INDEX idx_reading_sensor_time ON reading(sensor_id, reading_time);

-- Checks típicos por tipo de sensor seriam implementados por trigger/constraint específicas por sensor_type.
-- Para manter o DDL genérico, as faixas são validadas na aplicação (ou por tabelas de parâmetros).

CREATE TABLE label (
  label_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sensor_id     NUMBER,
  reading_time  TIMESTAMP(6),
  status        VARCHAR2(12) CHECK (status IN ('NORMAL','ANOMALO')),
  CONSTRAINT fk_label_sensor FOREIGN KEY (sensor_id) REFERENCES sensor(sensor_id)
);
